num_steps: 5000  # It equals to 200M frames.
batch_size: 32
N: 200
kappa: 1.0
lr: 5.e-5
memory_size: 100
gamma: 0.99
multi_step: 1
update_interval: 4
target_update_interval: 10
start_steps: 50
epsilon_train: 0.01
epsilon_eval: 0.001
epsilon_decay_steps: 250 # It equals to 1M frames.
double_q_learning: False
dueling_net: False
noisy_net: False
use_per: False
log_interval: 100
eval_interval: 250
num_eval_steps: 125  # It equals to 500k frames.
max_episode_steps: 27
grad_cliping:
